### ISSUE TITLE
hello,请教一下传值对象的问题

### ISSUE THREAD

**Issue by SongChao1123** [AllenChinese/vue-cli-easy#1]
![image](https://user-images.githubusercontent.com/10084365/32586681-05922b68-c53f-11e7-95b2-c9a48a2f99e4.png)

像这样的对象，在页面中如何传递给json文件呢

**Comment by AllenChinese** [comment]
不好意思，不太了解你想要解决的问题。我理解的是你需要进行占位符的编码或转义进行保存json对象

**Comment by AllenChinese** [comment]
不好意思，不太了解你想要解决的问题。我理解的是你需要进行占位符的编码或转义进行保存json对象

**Comment by SongChao1123** [comment]
已解决，{msg}
